/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>

#include "StdTypes.h"
#include "Utils.h"

#include "RCC_interface.h"
#include "GPIO_interface.h"
#include "SSeg_interface.h"
#include "KeyPad_interface.h"


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void Delay_ms(u32 Copy_u32Time)
{
	for (u32 i=0 ; i<Copy_u32Time ; i++)
	{
		for(u16 j=0 ; j<565 ; j++)
		{
			asm("NOP");
		}
	}
}

int main(void)
{
	u8 key=0,digits=0;

	RCC_voidInit();
	RCC_voidEnablePeripheralClock(RCC_APB2, RCC_GPIOA_ID);
	RCC_voidEnablePeripheralClock(RCC_APB2, RCC_GPIOB_ID);

	DIO_voidSetPortDirection(DIO_U8_PORTA, LOW, DIO_OUTPUT_2MHZ_PP);

	/*    To select Pull_Up u have to set the pin value to high according to Datasheet    */
	DIO_voidSetPinDirection(DIO_U8_PORTB, DIO_U8_PIN8, DIO_INPUT_PULL_UP_DOWN);
	DIO_voidSetPinValue(DIO_U8_PORTB, DIO_U8_PIN8, DIO_U8_HIGH);
	DIO_voidSetPinDirection(DIO_U8_PORTB, DIO_U8_PIN9, DIO_INPUT_PULL_UP_DOWN);
	DIO_voidSetPinValue(DIO_U8_PORTB, DIO_U8_PIN9, DIO_U8_HIGH);
	DIO_voidSetPinDirection(DIO_U8_PORTB, DIO_U8_PIN10, DIO_INPUT_PULL_UP_DOWN);
	DIO_voidSetPinValue(DIO_U8_PORTB, DIO_U8_PIN10, DIO_U8_HIGH);
	DIO_voidSetPinDirection(DIO_U8_PORTB, DIO_U8_PIN11, DIO_INPUT_PULL_UP_DOWN);
	DIO_voidSetPinValue(DIO_U8_PORTB, DIO_U8_PIN11, DIO_U8_HIGH);

	DIO_voidSetPinDirection(DIO_U8_PORTB, DIO_U8_PIN12, DIO_OUTPUT_2MHZ_PP);
	DIO_voidSetPinDirection(DIO_U8_PORTB, DIO_U8_PIN13, DIO_OUTPUT_2MHZ_PP);
	DIO_voidSetPinDirection(DIO_U8_PORTB, DIO_U8_PIN14, DIO_OUTPUT_2MHZ_PP);
	DIO_voidSetPinDirection(DIO_U8_PORTB, DIO_U8_PIN15, DIO_OUTPUT_2MHZ_PP);
	SSEG_VoidDisplayNumber(0);

	while(1)       //to press on keypad
	{
		DIO_voidSetPinValue(DIO_U8_PORTA, DIO_U8_PIN7, DIO_U8_HIGH);

		key=KeyPad_u8GetKey();
		if(key>='0' && key<='9')
		{
			digits=0;
			digits=digits*10;
			digits=digits+(key-'0');
			SSEG_VoidDisplayNumber(digits);
		}
	}
}

