/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "StdTypes.h"
#include "Utils.h"

#include "RCC_interface.h"
#include "GPIO_interface.h"


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


void Delay_ms(u32 Copy_u32Time)
{
	for (u32 i=0 ; i<Copy_u32Time ; i++)
	{
		for(u16 j=0 ; j<565 ; j++)
		{
			asm("NOP");
		}
	}
}

void LED_Pattern1(void)
{
	u8 j=0;
	while(j<2)
	{
		for (u8 i=0;i<8; i++)
		{
			DIO_voidSetPinValue(DIO_U8_PORTA,i,DIO_U8_HIGH);
			Delay_ms(300);
			DIO_voidSetPinValue(DIO_U8_PORTA,i,DIO_U8_LOW);
		}
		j++;
	}
}


void LED_Pattern2(void)
{
	u8 j=7;
	for (u8 i=0;i<4 && j>=4; i++)
	{
		DIO_voidSetPinValue(DIO_U8_PORTA,i,DIO_U8_HIGH);
		DIO_voidSetPinValue(DIO_U8_PORTA,j,DIO_U8_HIGH);
		Delay_ms(300);
		j--;
	}
	j=7;
	for (u8 i=0;i<4 && j>=4; i++)
	{
		DIO_voidSetPinValue(DIO_U8_PORTA,i,DIO_U8_LOW);
		DIO_voidSetPinValue(DIO_U8_PORTA,j,DIO_U8_LOW);
		Delay_ms(300);
		j--;
	}
}

void LED_Pattern3(void)
{
	u8 j=7;
	for (u8 i=0;i<4 && j>=4; i++)
	{
		DIO_voidSetPinValue(DIO_U8_PORTA,i,DIO_U8_HIGH);
		DIO_voidSetPinValue(DIO_U8_PORTA,j,DIO_U8_HIGH);
		Delay_ms(300);
		DIO_voidSetPinValue(DIO_U8_PORTA,i,DIO_U8_LOW);
		DIO_voidSetPinValue(DIO_U8_PORTA,j,DIO_U8_LOW);
		Delay_ms(50);
		j--;
	}
}
void LED_Pattern4(void)
{
	u8 j=0;
	while(j<2)
	{
		for (u8 i=0;i<8; i++)
		{
			DIO_voidSetPinValue(DIO_U8_PORTA,i,DIO_U8_HIGH);
			DIO_voidSetPinValue(DIO_U8_PORTA,i+1,DIO_U8_HIGH);
			Delay_ms(300);
			DIO_voidSetPinValue(DIO_U8_PORTA,i,DIO_U8_LOW);
			DIO_voidSetPinValue(DIO_U8_PORTA,i+1,DIO_U8_LOW);
			Delay_ms(50);
			i++;
		}
		j++;
	}
}

int main(void)
{
	RCC_voidInit();
	RCC_voidEnablePeripheralClock(RCC_APB2, RCC_GPIOA_ID);
	DIO_voidSetPortDirection(DIO_U8_PORTA,LOW,DIO_OUTPUT_2MHZ_PP);
	while(1)
	{
		LED_Pattern1();
		Delay_ms(200);
		LED_Pattern2();
		Delay_ms(200);
		LED_Pattern3();
		Delay_ms(200);
		LED_Pattern4();
		Delay_ms(200);
	}
}
